# server 변수 설정
@server = http://localhost:3000

### GET 요청 보내기
GET {{server}}/person

### POST
POST {{server}}/person
Content-Type: application/json

{
  "name": "Andy Park",
  "age": 30,
  "email": "andy@backend.com"
}

### GET 
GET {{server}}/person/andy@backend.com

### PUT
PUT {{server}}/person/andy@backend.com
Content-Type: application/json

{
  "age": 32
}

### DELETE
DELETE {{server}}/person/andy@backend.com