### Create 
POST http://localhost:3000/user/create
content-type: application/json

{
  "username": "andy",
  "password": "test1234",
  "email": "andy@podo.com"
}

### GetUser
GET http://localhost:3000/user/getUser/andy1@podo.com

### Update User
PUT http://localhost:3000/user/update/andy@podo.com
content-type: application/json

{
  "username": "andy2",
  "password": "test12345",
  "email": "andy@podo.com"
}

### Delete User
DELETE http://localhost:3000/user/delete/andy@podo.com

### Error Case: Invalid Email
POST http://localhost:3000/user/create
content-type: application/json

{
  "username": "andy",
  "password": "test1234",
  "email": "andy-podo"
}